version: "3.9"
services:
    my_mongodb:
        image: "mongo:4.4.6"
        restart: unless-stopped
        ports:
            - 27017-27019:27017-27019
        volumes:
            - cb-mongo:/data/db
    content-browser:
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - my_mongodb
volumes:
    cb-mongo:
